package com.game.adventuregame.controller;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class NonPlayableCharacterRepository {
    private static String[] names;

    static {
        names = new String[] {"Talos the Stone First",
                "Klotho the Joyful",
                "Kadmos the Masher",
                "Exekias the Legend",
                "Onias the Dungheap",
                "Thalestris the Resplendent",
                "Hippoklides the Durable",
                "Hestia the Toothless",
                "Kleobis the Lucky Drunk",
                "Doriskos the Insignificant",
                "Andrina the Keto",
                "Plyartes the Obscene",
                "Gorgos the Mouth",
                "Prokne the Hoplite Killer",
                "Phileotios the Blundering",
                "Theos the Hot-Footed",
                "Xanthos the Hen-Hearted",
                "Tekton the Art Collector",
                "Eirene the Stone Heart",
                "Rhadamanthos the Lion Tamer",
                "Makarias of Oversea",
                "Agnes, Lover of Hades",
                "Perimos the Survivor",
                "Vasilis the King of the Arena",
                "Titos, the Rock of Athens",
                "Evanthe, the Huntress",
                "Belos, the Beast of Sparta",
                "Klaudios, the King of Bandits",
                "Polyas the Thespian",
                "Philolaos the Sacrificial",
                "Tisiphone the Snake's Fang",
                "Photina the Wrath of Persephone",
                "Lysandra the Patricidal",
                "Doris the Translucent",
                "Tirynthios the Vigilant",
                "Eos the Smoldering",
                "Echemos of the Ashen Wake",
                "Metrobios the Bloodthirsty",
                "Iphito the Frenzied",
                "Keril the Heroic Poet",
                "Eionios the Weaver",
                "Ikarios the Tongue-Tied",
                "Timonax the One-Eyed",
                "Nir the Whirling Blade",
                "Aura the Spark",
                "Hypatia the Flash",
                "Margarites the Cursed",
                "Nora the Snow Leopard",
                "Andrea the Marksman",
                "Kyrios the Master",
                "Larissa the Backbreaker",
                "Hyrkanos the Cunning",
                "Lavrentios the Long Haired",
                "Astrapios the Exiled",
                "Alektryon the Rooster",
                "Lysistrate the Wreath of Roses",
                "Daniil the Tactician",
                "Krike the Ebon Serpent",
                "Dimitrios the Cleaner",
                "Pylaios the Uncommitted",
                "Exdandros the Bloody Drizzle",
                "Yulios the Balanced",
                "Xanthippos the Sightless",
                "Okealos the Metal-Skinned",
                "Nyx, Brother's Keeper",
                "Four-Toed Nymphodoros",
                "Kalaria the Soul Taker",
                "Cheimonas of the Sacred Watch",
                "Danai the Scavenger",
                "Kressida, Man-Eater",
                "Nikolaos the Fearless Cook",
                "Kleoptoleme the Deranged",
                "Theodoros the Doorkeeper",
                "Klasar the Exasperated",
                "Shani the Gifted",
                "Hagias thing Room Cleaner",
                "Shoeless Ogarneos",
                "Satyros the Ever-Living",
                "Xanthe the Bow Blocker",
                "Rasmos the Talented",
                "Keousa the Fashion Soul",
                "Althea the Eye Gouger",
                "Xander the Poison King",
                "Euanthe fur Cave Woman",
                "Amara, War Seeker",
                "Pelagia fbt Disowned",
                "Eileithyia the Stubborn",
                "Illios the Bitter",
                "Hyllos the Impotent",
                "Parmenion the Soulless Walker",
                "Priam the Woods",
                "Perdix the Cannibal",
                "Praxis tbh Critic",
                "Elene the Blood Rose",
                "Airlea the Brave",
                "Timotheous the Clean",
                "Misenos the Sphinx",
                "Kalanthe the Swift Paw",
                "Arethousa, Wife of Hypnos",
                "Imbrios the Vengeful",
                "Aglea the Cedar",
                "Moliones of the Centaur",
                "Proktos fur Forsaken",
                "Odios the Wanderer",
                "Theokleia the Howling Terror",
                "Keneon the Plain Walker",
                "Theomestros the Poet",
                "Hermione thing Sea Witch",
                "Prothous, Master of Sharks",
                "Philometer the Renegade",
                "Pandaros the Multi Faced",
                "Theramenes the Savage",
                "Tisandros the Nonchalant",
                "Olympia the Huntress",
                "Hirpes the Burning Fury",
                "Philoxenos the Beast Caller"};
    }

    public static List<String> getNonPlayableCharacterNames() {
        return Arrays.asList(names);
    }
}
